"""drop_column_hashed_password_from_sales_points_table

Revision ID: 36197da49466
Revises: b9ca1ef85d71
Create Date: 2026-02-05 22:44:23.650009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36197da49466'
down_revision: Union[str, Sequence[str], None] = 'b9ca1ef85d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_points', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_points', sa.Column('hashed_password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
