"""delete_column_item_order_date_and_add_columns_amount_kg_liters_to_items_orders_table

Revision ID: 56f2cd233e40
Revises: 036f283eb233
Create Date: 2026-02-04 20:03:28.021099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer, Float


# revision identifiers, used by Alembic.
revision: str = '56f2cd233e40'
down_revision: Union[str, Sequence[str], None] = '036f283eb233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column("items_orders", "item_order_date")
    op.add_column("items_orders", sa.Column("amount", Integer, nullable=True))
    op.add_column("items_orders", sa.Column("kg", Float, nullable=True))
    op.add_column("items_orders", sa.Column("liters", Float, nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
