"""add_columns_email_and_password_to_sales_points_table

Revision ID: 7925e3a7dd86
Revises: 56f2cd233e40
Create Date: 2026-02-05 17:36:04.803554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7925e3a7dd86'
down_revision: Union[str, Sequence[str], None] = '56f2cd233e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('sales_points', sa.Column('email', sa.String()))
    op.add_column('sales_points', sa.Column('password', sa.String()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_points', 'password')
    op.drop_column('sales_points', 'email')
    # ### end Alembic commands ###
