"""add_column_hashed_password_to_sales_points_table

Revision ID: b9ca1ef85d71
Revises: e91fdfeaf84e
Create Date: 2026-02-05 21:37:41.202105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ca1ef85d71'
down_revision: Union[str, Sequence[str], None] = 'e91fdfeaf84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_points', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_points', 'hashed_password')
    # ### end Alembic commands ###
