"""create_order_sale_point_table

Revision ID: e91fdfeaf84e
Revises: 7925e3a7dd86
Create Date: 2026-02-05 18:34:00.818083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91fdfeaf84e'
down_revision: Union[str, Sequence[str], None] = '7925e3a7dd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
